version: "3.8"
services:
    webapp:
        depends_on: 
            - mongo-db
            - redis
        build: .
        ports:
            - "8080:8080"
    mongo-db:
        image: mongo
    redis:
        image: redis