version: "3.3"
services:
    webapp:
        depends_on: 
            - mongo-db
            - redis
        build: .
        ports:
            - "80:8080"
        volumes: 
            - labconnect-submissions:/var/labconnect/submissions
            - labconnect-assignments:/var/labconnect/assignments
    mongo-db:
        image: mongo
        volumes:
            - labconnect-mongo:/data/db
    redis:
        image: redis

volumes: 
    labconnect-submissions:
    labconnect-assignments:
    labconnect-mongo: