version: "3.7"
services:
    webapp:
        depends_on: 
            - mongo-db
            - redis
        build: .
        ports:
            - "80:8080"
        volumes: 
            - assignments:/var/labconnect/assignments
    mongo-db:
        image: mongo
        volumes:
            - mongodb:/data/db
    redis:
        image: redis

volumes: 
    assignments:
    mongodb: