version: "3.8"
services:
    webapp:
        depends_on: 
            - mongo-db
            - redis
        build: .
        ports:
            - "80:8080"
        volumes: 
            - submissions:/var/labconnect/submissions
            - assignments:/var/labconnect/assignments
    mongo-db:
        image: mongo
        volumes:
            - mongodb:/data/db
    redis:
        image: redis

volumes: 
    submissions:
    assignments:
    mongodb: