name: CI

on: [push, workflow_dispatch]

jobs:
  test-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - uses: berkan-sahin/latexmk-in-dir@v0.1
        with:
          directory: doc
