name: Build LaTeX document
on: 
  push:
    paths:
    - "doc/**"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            detailed-design-report.tex
          working_directory: doc/
      - name : Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: detailed-design-report.pdf
          
